package org.innereye.web.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.innereye.web.mbg.mapper.example.IeAccountExample;
import org.innereye.web.mbg.model.IeAccount;

public interface IeAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    long countByExample(IeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    int deleteByExample(IeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    int insertSelective(IeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    List<IeAccount> selectByExample(IeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    IeAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") IeAccount record, @Param("example") IeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ie_account
     *
     * @mbg.generated Wed Oct 18 15:26:03 CST 2017
     */
    int updateByPrimaryKeySelective(IeAccount record);
}